#!/usr/bin/env node
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

// Read contract artifacts
const artifactsDir = path.join(process.cwd(), '..', 'artifacts', 'contracts');
const contractsDir = path.join(process.cwd(), 'abi');

console.log('Reading contracts from artifacts directory:', artifactsDir);

// List of contracts to generate ABI for
const contracts = [
  'FHERaffle',
  'FHERaffleLocal'
];

// Ensure ABI directory exists
if (!fs.existsSync(contractsDir)) {
  fs.mkdirSync(contractsDir, { recursive: true });
  console.log('Created ABI directory:', contractsDir);
}

// Generate ABI for each contract
contracts.forEach(contractName => {
  const artifactPath = path.join(artifactsDir, `${contractName}.sol`, `${contractName}.json`);
  
  if (!fs.existsSync(artifactPath)) {
    console.warn(`Artifact not found: ${artifactPath}`);
    return;
  }

  console.log(`Processing ${contractName}...`);
  
  try {
    const artifact = JSON.parse(fs.readFileSync(artifactPath, 'utf8'));
    
    if (!artifact.abi) {
      console.warn(`No ABI found in ${artifactPath}`);
      return;
    }

    // Generate ABI file
    const abiOutput = {
      _format: 'hh-sol-artifact-1',
      contractName: contractName,
      sourceName: `${contractName}.sol`,
      abi: artifact.abi,
      bytecode: artifact.bytecode,
      deployedBytecode: artifact.deployedBytecode,
      metadata: artifact.metadata
    };

    const abiFilePath = path.join(contractsDir, `${contractName}ABI.ts`);
    
    // Generate TypeScript ABI file
    const abiContent = `// Auto-generated by genabi.mjs
// Timestamp: ${new Date().toISOString()}
import type { Abi } from '../abi/types';

export const ${contractName}ABI: Abi = ${JSON.stringify(artifact.abi, null, 2)};

export const deployedBytecode: string = "${artifact.deployedBytecode || ''}";
`;
    
    fs.writeFileSync(abiFilePath, abiContent, 'utf8');
    
    // Generate JSON ABI file
    const jsonFilePath = path.join(contractsDir, `${contractName}ABI.json`);
    fs.writeFileSync(jsonFilePath, JSON.stringify(abiOutput, null, 2), 'utf8');
    
    // Generate Address file if this is the local contract
    if (contractName === 'FHERaffleLocal') {
      const addressFilePath = path.join(contractsDir, 'FHERaffleLocalAddress.ts');
      const addressContent = `// Auto-generated by genabi.mjs
// Address of deployed FHERaffleLocal contract
export const CONTRACT_ADDRESS = '0x0000000000000000000000000000000000000000';

// Update this address after deployment
`;

      fs.writeFileSync(addressFilePath, addressContent, 'utf8');
      console.log(`Generated address file: ${addressFilePath}`);
    }
    
    console.log(`✅ Generated ABI for ${contractName}`);
    console.log(`   - TypeScript: ${abiFilePath}`);
    console.log(`   - JSON: ${jsonFilePath}`);
    
  } catch (error) {
    console.error(`Error processing ${contractName}:`, error);
    process.exit(1);
  }
});

console.log('✅ ABI generation complete!');
