import { task } from "hardhat/config";
import type { HardhatArguments, HardhatTask } from "hardhat/types";

const deployLocalTask: task("deploy-local", async function (
    args: HardhatArguments,
    hre: HardhatRuntimeEnvironment
) {
    console.log('🚀 Starting deployment of FHERaffleLocal to Hardhat network...');
    
    const { deployer } = await hre.getNamedAccounts();
    console.log('📝 Deployer address:', deployer);

    console.log('📄 Compiling FHERaffleLocal contract...');
    
    // Deploy local contract (without FHE)
    console.log('🚀 Deploying FHERaffleLocal contract...');
    const raffleContract = await hre.ethers.deployContract(
        'FHERaffleLocal',
        [],
        {}
    );

    await raffleContract.waitForDeployment();
    
    const address = await raffleContract.getAddress();
    console.log('✅ FHERaffleLocal deployed successfully!');
    console.log('📍 Contract address:', address);

    // Save deployment info
    const fs = require('fs');
    const path = require('path');
    
    console.log('💾 Saving deployment to deployments/localhost/FHERaffleLocal.json');
    const deploymentsDir = path.join(__dirname, '..', 'deployments', 'localhost');
    if (!fs.existsSync(deploymentsDir)) {
        fs.mkdirSync(deploymentsDir, { recursive: true });
    }
    
    const deploymentFile = path.join(deploymentsDir, 'FHERaffleLocal.json');
    const deploymentData = {
        network: 'localhost',
        chainId: 31337,
        address: address,
        deployer: deployer.address,
        transactionHash: raffleContract.deploymentTransaction()?.hash,
        timestamp: new Date().toISOString()
    };
    
    fs.writeFileSync(deploymentFile, JSON.stringify(deploymentData, null, 2), 'utf8');
    console.log('💾 Deployment saved to:', deploymentFile);

    // Generate contract ABI in ui directory
    const uiDir = path.join(__dirname, '..', 'ui', 'abi');
    if (!fs.existsSync(uiDir)) {
        fs.mkdirSync(uiDir, { recursive: true });
    }
    
    const artifact = await hre.artifacts.readArtifact('FHERaffleLocal');
    
    // Generate ABI files
    const abiFile = path.join(uiDir, 'FHERaffleLocalABI.ts');
    const jsonAbiFile = path.join(uiDir, 'FHERaffleLocalABI.json');
    const addressFile = path.join(uiDir, 'FHERaffleLocalAddress.ts');
    
    // Generate TypeScript ABI
    const abiContent = `// Auto-generated by tasks/deploy-local.ts
// Timestamp: ${new Date().toISOString()}
import type { Abi } from '../abi/types';

export const FHERaffleLocalABI: Abi = ${JSON.stringify(artifact.abi, null, 2)};
`;
    
    fs.writeFileSync(abiFile, abiContent, 'utf8');
    
    // Generate JSON ABI
    const jsonAbiOutput = artifact.abi;
    fs.writeFileSync(jsonAbiFile, JSON.stringify(jsonAbiOutput, null, 2), 'utf8');
    
    // Generate address file
    const addressContent = `// Auto-generated by tasks/deploy-local.ts
// Address of deployed FHERaffleLocal contract
export const CONTRACT_ADDRESS = '${address}';

// Update this in contracts.ts: 
// const LOCAL_CONTRACT_ADDRESS = '${address}';
`;
    fs.writeFileSync(addressFile, addressContent, 'utf8');
    
    console.log('✅ ABI files generated in ui/abi/');
    console.log(`   - ${abiFile}`);
    console.log(`   - ${jsonAbiFile}`);
    console.log(`   - ${addressFile}`);

    console.log('🎉 Deployment complete!');
    console.log('');
    console.log('📖 Update contract address in UI if needed:');
    console.log('   The contract address is:', address);
    console.log('   It has been saved to: ui/abi/FHERaffleLocalAddress.ts');
    console.log('   No manual .env configuration needed!');

    return {
        FHERaffleLocal: {
            address: address,
            deployer: deployer.address
        }
    };
};

// Tags for hardhat-deploy
deployLocalTask.tags = ['FHERaffleLocal'];

// Only deploy to localhost
export default deployLocalTask;
