import { DeployFunction } from 'hardhat-deploy/types';

const deploy: DeployFunction<Record<string, never>> = async function (
    hre
) {
    const { deployer } = await hre.getNamedAccounts();
    
    console.log('Deploying FHERaffleLocal contract...');
    console.log('Deployer address:', deployer);

    // Deploy the local contract (without FHE)
    const raffleContract = await hre.ethers.deployContract(
        'FHERaffleLocal',
        [],
        {}
    );

    await raffleContract.waitForDeployment();
    
    const address = await raffleContract.getAddress();
    console.log('FHERaffleLocal deployed to:', address);

    // Save deployment info
    console.log('Saving deployment to deployments/localhost/FHERaffleLocal.json');
    const fs = require('fs');
    const path = require('path');
    
    const deploymentDir = path.join(__dirname, '..', 'deployments', 'localhost');
    if (!fs.existsSync(deploymentDir)) {
        fs.mkdirSync(deploymentDir, { recursive: true });
    }
    
    const deploymentFile = path.join(deploymentDir, 'FHERaffleLocal.json');
    const deploymentData = {
        network: 'localhost',
        chainId: '31337',
        address: address,
        deployer: deployer.address,
        transactionHash: raffleContract.deploymentTransaction()?.hash,
        timestamp: new Date().toISOString()
    };
    
    fs.writeFileSync(deploymentFile, JSON.stringify(deploymentData, null, 2), 'utf8');
    console.log('Deployment saved to:', deploymentFile);

    // Generate contract ABI in ui directory
    const uiDir = path.join(__dirname, '..', 'ui', 'abi');
    if (!fs.existsSync(uiDir)) {
        fs.mkdirSync(uiDir, { recursive: true });
    }
    
    const artifact = await hre.artifacts.readArtifact('FHERaffleLocal');
    
    // Generate ABI files
    const abiFile = path.join(uiDir, 'FHERaffleLocalABI.ts');
    const jsonAbiFile = path.join(uiDir, 'FHERaffleLocalABI.json');
    const addressFile = path.join(uiDir, 'FHERaffleLocalAddress.ts');
    
    // Generate TypeScript ABI
    const abiContent = `// Auto-generated by deploy-local.js
// Timestamp: ${new Date().toISOString()}
import type { Abi } from '../abi/types';

export const FHERaffleLocalABI: Abi = ${JSON.stringify(artifact.abi, null, 2)};

export const deployedBytecode: string = "${artifact.deployedBytecode || ''}";
`;
    fs.writeFileSync(abiFile, abiContent, 'utf8');
    
    // Generate JSON ABI
    fs.writeFileSync(jsonAbiFile, JSON.stringify(artifact.abi, null, 2), 'utf8');
    
    // Generate address file
    const addressContent = `// Auto-generated by deploy-local.js
// Address of deployed FHERaffleLocal contract
export const CONTRACT_ADDRESS = '${address}';

// Update this in contracts.ts: 
// const LOCAL_CONTRACT_ADDRESS = '${address}';`;
    fs.writeFileSync(addressFile, addressContent, 'utf8');
    
    console.log('✅ ABI files generated in ui/abi/');
    console.log(`   - ${abiFile}`);
    console.log(`   - ${jsonAbiFile}`);
    console.log(`   - ${addressFile}`);

    return {
        FHERaffleLocal: {
            address: address,
            deployer: deployer.address
        }
    };
};

// Tags for hardhat-deploy
deploy.tags = ['FHERaffleLocal'];

// Only deploy to localhost
export default deploy;

