/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface FHERaffleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createRaffle"
      | "drawWinner"
      | "enterRaffle"
      | "getEntry"
      | "getEntryCount"
      | "getEntryFee"
      | "getPrizeAmount"
      | "getRaffleCount"
      | "getRaffleMeta"
      | "hasEntered"
      | "protocolId"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "EntrySubmitted" | "RaffleCreated" | "RaffleDrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createRaffle",
    values: [
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "drawWinner",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "enterRaffle",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEntry",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEntryCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEntryFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPrizeAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRaffleCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRaffleMeta",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasEntered",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "createRaffle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "drawWinner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "enterRaffle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getEntry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getEntryCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEntryFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPrizeAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRaffleCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRaffleMeta",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasEntered", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
}

export namespace EntrySubmittedEvent {
  export type InputTuple = [
    raffleId: BigNumberish,
    participant: AddressLike,
    createdAt: BigNumberish
  ];
  export type OutputTuple = [
    raffleId: bigint,
    participant: string,
    createdAt: bigint
  ];
  export interface OutputObject {
    raffleId: bigint;
    participant: string;
    createdAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RaffleCreatedEvent {
  export type InputTuple = [
    raffleId: BigNumberish,
    creator: AddressLike,
    title: string,
    createdAt: BigNumberish
  ];
  export type OutputTuple = [
    raffleId: bigint,
    creator: string,
    title: string,
    createdAt: bigint
  ];
  export interface OutputObject {
    raffleId: bigint;
    creator: string;
    title: string;
    createdAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RaffleDrawnEvent {
  export type InputTuple = [
    raffleId: BigNumberish,
    winner: AddressLike,
    drawnAt: BigNumberish
  ];
  export type OutputTuple = [raffleId: bigint, winner: string, drawnAt: bigint];
  export interface OutputObject {
    raffleId: bigint;
    winner: string;
    drawnAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FHERaffle extends BaseContract {
  connect(runner?: ContractRunner | null): FHERaffle;
  waitForDeployment(): Promise<this>;

  interface: FHERaffleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createRaffle: TypedContractMethod<
    [
      title: string,
      description: string,
      prizeAmount: BigNumberish,
      entryFee: BigNumberish,
      maxEntries: BigNumberish,
      durationHours: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  drawWinner: TypedContractMethod<
    [raffleId: BigNumberish],
    [void],
    "nonpayable"
  >;

  enterRaffle: TypedContractMethod<
    [raffleId: BigNumberish, encAmount: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getEntry: TypedContractMethod<
    [raffleId: BigNumberish, entryIndex: BigNumberish],
    [
      [string, string, bigint] & {
        encAmount: string;
        participant: string;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  getEntryCount: TypedContractMethod<
    [raffleId: BigNumberish],
    [bigint],
    "view"
  >;

  getEntryFee: TypedContractMethod<[raffleId: BigNumberish], [bigint], "view">;

  getPrizeAmount: TypedContractMethod<
    [raffleId: BigNumberish],
    [bigint],
    "view"
  >;

  getRaffleCount: TypedContractMethod<[], [bigint], "view">;

  getRaffleMeta: TypedContractMethod<
    [raffleId: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        string,
        bigint
      ] & {
        creator: string;
        title: string;
        description: string;
        prizeAmount: bigint;
        entryFee: bigint;
        maxEntries: bigint;
        currentEntries: bigint;
        expireAt: bigint;
        isActive: boolean;
        isDrawn: boolean;
        winner: string;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  hasEntered: TypedContractMethod<
    [raffleId: BigNumberish, participant: AddressLike],
    [boolean],
    "view"
  >;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createRaffle"
  ): TypedContractMethod<
    [
      title: string,
      description: string,
      prizeAmount: BigNumberish,
      entryFee: BigNumberish,
      maxEntries: BigNumberish,
      durationHours: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "drawWinner"
  ): TypedContractMethod<[raffleId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "enterRaffle"
  ): TypedContractMethod<
    [raffleId: BigNumberish, encAmount: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getEntry"
  ): TypedContractMethod<
    [raffleId: BigNumberish, entryIndex: BigNumberish],
    [
      [string, string, bigint] & {
        encAmount: string;
        participant: string;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEntryCount"
  ): TypedContractMethod<[raffleId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEntryFee"
  ): TypedContractMethod<[raffleId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPrizeAmount"
  ): TypedContractMethod<[raffleId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRaffleCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRaffleMeta"
  ): TypedContractMethod<
    [raffleId: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        string,
        bigint
      ] & {
        creator: string;
        title: string;
        description: string;
        prizeAmount: bigint;
        entryFee: bigint;
        maxEntries: bigint;
        currentEntries: bigint;
        expireAt: bigint;
        isActive: boolean;
        isDrawn: boolean;
        winner: string;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasEntered"
  ): TypedContractMethod<
    [raffleId: BigNumberish, participant: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "EntrySubmitted"
  ): TypedContractEvent<
    EntrySubmittedEvent.InputTuple,
    EntrySubmittedEvent.OutputTuple,
    EntrySubmittedEvent.OutputObject
  >;
  getEvent(
    key: "RaffleCreated"
  ): TypedContractEvent<
    RaffleCreatedEvent.InputTuple,
    RaffleCreatedEvent.OutputTuple,
    RaffleCreatedEvent.OutputObject
  >;
  getEvent(
    key: "RaffleDrawn"
  ): TypedContractEvent<
    RaffleDrawnEvent.InputTuple,
    RaffleDrawnEvent.OutputTuple,
    RaffleDrawnEvent.OutputObject
  >;

  filters: {
    "EntrySubmitted(uint256,address,uint64)": TypedContractEvent<
      EntrySubmittedEvent.InputTuple,
      EntrySubmittedEvent.OutputTuple,
      EntrySubmittedEvent.OutputObject
    >;
    EntrySubmitted: TypedContractEvent<
      EntrySubmittedEvent.InputTuple,
      EntrySubmittedEvent.OutputTuple,
      EntrySubmittedEvent.OutputObject
    >;

    "RaffleCreated(uint256,address,string,uint64)": TypedContractEvent<
      RaffleCreatedEvent.InputTuple,
      RaffleCreatedEvent.OutputTuple,
      RaffleCreatedEvent.OutputObject
    >;
    RaffleCreated: TypedContractEvent<
      RaffleCreatedEvent.InputTuple,
      RaffleCreatedEvent.OutputTuple,
      RaffleCreatedEvent.OutputObject
    >;

    "RaffleDrawn(uint256,address,uint64)": TypedContractEvent<
      RaffleDrawnEvent.InputTuple,
      RaffleDrawnEvent.OutputTuple,
      RaffleDrawnEvent.OutputObject
    >;
    RaffleDrawn: TypedContractEvent<
      RaffleDrawnEvent.InputTuple,
      RaffleDrawnEvent.OutputTuple,
      RaffleDrawnEvent.OutputObject
    >;
  };
}
