/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FHECounter } from "./FHECounter";
export type { FHERaffle } from "./FHERaffle";
export type { FHERaffleLocal } from "./FHERaffleLocal";
